[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
justin_test_token = "AEctW6F7a9itJ3ESTtHHzmnr6EXGcwy4ssFfD3LGKDGu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
